<?php


namespace Domain\Card\DataTransferObject;


use Spatie\DataTransferObject\DataTransferObject;

class CardData extends DataTransferObject
{

    public static function fromRequest(array $arrayOfParameters): array
    {
        return parent::arrayOf($arrayOfParameters); // TODO: Change the autogenerated stub
    }

}